<?php

use Illuminate\Database\Seeder;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(){
        DB::table('countries')->insert([['name'=>'Abkhazia','code_alpha2'=>'AB','code_alpha3'=>'ABH'],
            ['name'=>'Afghanistan','code_alpha2'=>'AF','code_alpha3'=>'AFG'],
            ['name'=>'Albania','code_alpha2'=>'AL','code_alpha3'=>'ALB'],
            ['name'=>'Algeria','code_alpha2'=>'DZ','code_alpha3'=>'DZA'],
            ['name'=>'American Samoa','code_alpha2'=>'AS','code_alpha3'=>'ASM'],
            ['name'=>'Andorra','code_alpha2'=>'AD','code_alpha3'=>'AND'],
            ['name'=>'Angola','code_alpha2'=>'AO','code_alpha3'=>'AGO'],
            ['name'=>'Anguilla','code_alpha2'=>'AI','code_alpha3'=>'AIA'],
            ['name'=>'Antarctica','code_alpha2'=>'AQ','code_alpha3'=>'ATA'],
            ['name'=>'Antigua and Barbuda','code_alpha2'=>'AG','code_alpha3'=>'ATG'],
            ['name'=>'Argentina','code_alpha2'=>'AR','code_alpha3'=>'ARG'],
            ['name'=>'Armenia','code_alpha2'=>'AM','code_alpha3'=>'ARM'],
            ['name'=>'Aruba','code_alpha2'=>'AW','code_alpha3'=>'ABW'],
            ['name'=>'Australia','code_alpha2'=>'AU','code_alpha3'=>'AUS'],
            ['name'=>'Austria','code_alpha2'=>'AT','code_alpha3'=>'AUT'],
            ['name'=>'Azerbaijan','code_alpha2'=>'AZ','code_alpha3'=>'AZE'],
            ['name'=>'Bahamas','code_alpha2'=>'BS','code_alpha3'=>'BHS'],
            ['name'=>'Bahrain','code_alpha2'=>'BH','code_alpha3'=>'BHR'],
            ['name'=>'Bangladesh','code_alpha2'=>'BD','code_alpha3'=>'BGD'],
            ['name'=>'Barbados','code_alpha2'=>'BB','code_alpha3'=>'BRB'],
            ['name'=>'Belarus','code_alpha2'=>'BY','code_alpha3'=>'BLR'],
            ['name'=>'Belgium','code_alpha2'=>'BE','code_alpha3'=>'BEL'],
            ['name'=>'Belize','code_alpha2'=>'BZ','code_alpha3'=>'BLZ'],
            ['name'=>'Benin','code_alpha2'=>'BJ','code_alpha3'=>'BEN'],
            ['name'=>'Bermuda','code_alpha2'=>'BM','code_alpha3'=>'BMU'],
            ['name'=>'Bhutan','code_alpha2'=>'BT','code_alpha3'=>'BTN'],
            ['name'=>'Bolivia, plurinational state of','code_alpha2'=>'BO','code_alpha3'=>'BOL'],
            ['name'=>'Bonaire, Sint Eustatius and Saba','code_alpha2'=>'BQ','code_alpha3'=>'BES'],
            ['name'=>'Bosnia and Herzegovina','code_alpha2'=>'BA','code_alpha3'=>'BIH'],
            ['name'=>'Botswana','code_alpha2'=>'BW','code_alpha3'=>'BWA'],
            ['name'=>'Bouvet Island','code_alpha2'=>'BV','code_alpha3'=>'BVT'],
            ['name'=>'Brazil','code_alpha2'=>'BR','code_alpha3'=>'BRA'],
            ['name'=>'British Indian Ocean Territory','code_alpha2'=>'IO','code_alpha3'=>'IOT'],
            ['name'=>'Brunei Darussalam','code_alpha2'=>'BN','code_alpha3'=>'BRN'],
            ['name'=>'Bulgaria','code_alpha2'=>'BG','code_alpha3'=>'BGR'],
            ['name'=>'Burkina Faso','code_alpha2'=>'BF','code_alpha3'=>'BFA'],
            ['name'=>'Burma','code_alpha2'=>'MM','code_alpha3'=>'MMR'],
            ['name'=>'Burundi','code_alpha2'=>'BI','code_alpha3'=>'BDI'],
            ['name'=>'Cambodia','code_alpha2'=>'KH','code_alpha3'=>'KHM'],
            ['name'=>'Cameroon','code_alpha2'=>'CM','code_alpha3'=>'CMR'],
            ['name'=>'Canada','code_alpha2'=>'CA','code_alpha3'=>'CAN'],
            ['name'=>'Cape Verde','code_alpha2'=>'CV','code_alpha3'=>'CPV'],
            ['name'=>'Cayman Islands','code_alpha2'=>'KY','code_alpha3'=>'CYM'],
            ['name'=>'Central African Republic','code_alpha2'=>'CF','code_alpha3'=>'CAF'],
            ['name'=>'Chad','code_alpha2'=>'TD','code_alpha3'=>'TCD'],
            ['name'=>'Chile','code_alpha2'=>'CL','code_alpha3'=>'CHL'],
            ['name'=>'China','code_alpha2'=>'CN','code_alpha3'=>'CHN'],
            ['name'=>'Christmas Island','code_alpha2'=>'CX','code_alpha3'=>'CXR'],
            ['name'=>'Cocos (Keeling) Islands','code_alpha2'=>'CC','code_alpha3'=>'CCK'],
            ['name'=>'Colombia','code_alpha2'=>'CO','code_alpha3'=>'COL'],
            ['name'=>'Comoros','code_alpha2'=>'KM','code_alpha3'=>'COM'],
            ['name'=>'Congo','code_alpha2'=>'CG','code_alpha3'=>'COG'],
            ['name'=>'Congo, Democratic Republic of the','code_alpha2'=>'CD','code_alpha3'=>'COD'],
            ['name'=>'Cook Islands','code_alpha2'=>'CK','code_alpha3'=>'COK'],
            ['name'=>'Costa Rica','code_alpha2'=>'CR','code_alpha3'=>'CRI'],
            ['name'=>'Cote dIvoire','code_alpha2'=>'CI','code_alpha3'=>'CIV'],
            ['name'=>'Croatia','code_alpha2'=>'HR','code_alpha3'=>'HRV'],
            ['name'=>'Cuba','code_alpha2'=>'CU','code_alpha3'=>'CUB'],
            ['name'=>'Curaçao','code_alpha2'=>'CW','code_alpha3'=>'CUW'],
            ['name'=>'Cyprus','code_alpha2'=>'CY','code_alpha3'=>'CYP'],
            ['name'=>'Czech Republic','code_alpha2'=>'CZ','code_alpha3'=>'CZE'],
            ['name'=>'Denmark','code_alpha2'=>'DK','code_alpha3'=>'DNK'],
            ['name'=>'Djibouti','code_alpha2'=>'DJ','code_alpha3'=>'DJI'],
            ['name'=>'Dominica','code_alpha2'=>'DM','code_alpha3'=>'DMA'],
            ['name'=>'Dominican Republic','code_alpha2'=>'DO','code_alpha3'=>'DOM'],
            ['name'=>'Ecuador','code_alpha2'=>'EC','code_alpha3'=>'ECU'],
            ['name'=>'Egypt','code_alpha2'=>'EG','code_alpha3'=>'EGY'],
            ['name'=>'El Salvador','code_alpha2'=>'SV','code_alpha3'=>'SLV'],
            ['name'=>'Equatorial Guinea','code_alpha2'=>'GQ','code_alpha3'=>'GNQ'],
            ['name'=>'Eritrea','code_alpha2'=>'ER','code_alpha3'=>'ERI'],
            ['name'=>'Estonia','code_alpha2'=>'EE','code_alpha3'=>'EST'],
            ['name'=>'Eswatini','code_alpha2'=>'SZ','code_alpha3'=>'SWZ'],
            ['name'=>'Ethiopia','code_alpha2'=>'ET','code_alpha3'=>'ETH'],
            ['name'=>'Falkland Islands (Malvinas)','code_alpha2'=>'FK','code_alpha3'=>'FLK'],
            ['name'=>'Faroe Islands','code_alpha2'=>'FO','code_alpha3'=>'FRO'],
            ['name'=>'Fiji','code_alpha2'=>'FJ','code_alpha3'=>'FJI'],
            ['name'=>'Finland','code_alpha2'=>'FI','code_alpha3'=>'FIN'],
            ['name'=>'France','code_alpha2'=>'FR','code_alpha3'=>'FRA'],
            ['name'=>'French Guiana','code_alpha2'=>'GF','code_alpha3'=>'GUF'],
            ['name'=>'French Polynesia','code_alpha2'=>'PF','code_alpha3'=>'PYF'],
            ['name'=>'French Southern Territories','code_alpha2'=>'TF','code_alpha3'=>'ATF'],
            ['name'=>'Gabon','code_alpha2'=>'GA','code_alpha3'=>'GAB'],
            ['name'=>'Gambia','code_alpha2'=>'GM','code_alpha3'=>'GMB'],
            ['name'=>'Georgia','code_alpha2'=>'GE','code_alpha3'=>'GEO'],
            ['name'=>'Germany','code_alpha2'=>'DE','code_alpha3'=>'DEU'],
            ['name'=>'Ghana','code_alpha2'=>'GH','code_alpha3'=>'GHA'],
            ['name'=>'Gibraltar','code_alpha2'=>'GI','code_alpha3'=>'GIB'],
            ['name'=>'Greece','code_alpha2'=>'GR','code_alpha3'=>'GRC'],
            ['name'=>'Greenland','code_alpha2'=>'GL','code_alpha3'=>'GRL'],
            ['name'=>'Grenada','code_alpha2'=>'GD','code_alpha3'=>'GRD'],
            ['name'=>'Guadeloupe','code_alpha2'=>'GP','code_alpha3'=>'GLP'],
            ['name'=>'Guam','code_alpha2'=>'GU','code_alpha3'=>'GUM'],
            ['name'=>'Guatemala','code_alpha2'=>'GT','code_alpha3'=>'GTM'],
            ['name'=>'Guernsey','code_alpha2'=>'GG','code_alpha3'=>'GGY'],
            ['name'=>'Guinea','code_alpha2'=>'GN','code_alpha3'=>'GIN'],
            ['name'=>'Guinea-Bissau','code_alpha2'=>'GW','code_alpha3'=>'GNB'],
            ['name'=>'Guyana','code_alpha2'=>'GY','code_alpha3'=>'GUY'],
            ['name'=>'Haiti','code_alpha2'=>'HT','code_alpha3'=>'HTI'],
            ['name'=>'Heard Island and McDonald Islands','code_alpha2'=>'HM','code_alpha3'=>'HMD'],
            ['name'=>'Holy See (Vatican City State)','code_alpha2'=>'VA','code_alpha3'=>'VAT'],
            ['name'=>'Honduras','code_alpha2'=>'HN','code_alpha3'=>'HND'],
            ['name'=>'Hong Kong','code_alpha2'=>'HK','code_alpha3'=>'HKG'],
            ['name'=>'Hungary','code_alpha2'=>'HU','code_alpha3'=>'HUN'],
            ['name'=>'Iceland','code_alpha2'=>'IS','code_alpha3'=>'ISL'],
            ['name'=>'India','code_alpha2'=>'IN','code_alpha3'=>'IND'],
            ['name'=>'Indonesia','code_alpha2'=>'ID','code_alpha3'=>'IDN'],
            ['name'=>'Iran, Islamic Republic of','code_alpha2'=>'IR','code_alpha3'=>'IRN'],
            ['name'=>'Iraq','code_alpha2'=>'IQ','code_alpha3'=>'IRQ'],
            ['name'=>'Ireland','code_alpha2'=>'IE','code_alpha3'=>'IRL'],
            ['name'=>'Isle of Man','code_alpha2'=>'IM','code_alpha3'=>'IMN'],
            ['name'=>'Israel','code_alpha2'=>'IL','code_alpha3'=>'ISR'],
            ['name'=>'Italy','code_alpha2'=>'IT','code_alpha3'=>'ITA'],
            ['name'=>'Jamaica','code_alpha2'=>'JM','code_alpha3'=>'JAM'],
            ['name'=>'Japan','code_alpha2'=>'JP','code_alpha3'=>'JPN'],
            ['name'=>'Jersey','code_alpha2'=>'JE','code_alpha3'=>'JEY'],
            ['name'=>'Jordan','code_alpha2'=>'JO','code_alpha3'=>'JOR'],
            ['name'=>'Kazakhstan','code_alpha2'=>'KZ','code_alpha3'=>'KAZ'],
            ['name'=>'Kenya','code_alpha2'=>'KE','code_alpha3'=>'KEN'],
            ['name'=>'Kiribati','code_alpha2'=>'KI','code_alpha3'=>'KIR'],
            ['name'=>'Korea, Democratic Peoples republic of','code_alpha2'=>'KP','code_alpha3'=>'PRK'],
            ['name'=>'Korea, Republic of','code_alpha2'=>'KR','code_alpha3'=>'KOR'],
            ['name'=>'Kuwait','code_alpha2'=>'KW','code_alpha3'=>'KWT'],
            ['name'=>'Kyrgyzstan','code_alpha2'=>'KG','code_alpha3'=>'KGZ'],
            ['name'=>'Lao Peoples Democratic Republic','code_alpha2'=>'LA','code_alpha3'=>'LAO'],
            ['name'=>'Latvia','code_alpha2'=>'LV','code_alpha3'=>'LVA'],
            ['name'=>'Lebanon','code_alpha2'=>'LB','code_alpha3'=>'LBN'],
            ['name'=>'Lesotho','code_alpha2'=>'LS','code_alpha3'=>'LSO'],
            ['name'=>'Liberia','code_alpha2'=>'LR','code_alpha3'=>'LBR'],
            ['name'=>'Libyan Arab Jamahiriya','code_alpha2'=>'LY','code_alpha3'=>'LBY'],
            ['name'=>'Liechtenstein','code_alpha2'=>'LI','code_alpha3'=>'LIE'],
            ['name'=>'Lithuania','code_alpha2'=>'LT','code_alpha3'=>'LTU'],
            ['name'=>'Luxembourg','code_alpha2'=>'LU','code_alpha3'=>'LUX'],
            ['name'=>'Macao','code_alpha2'=>'MO','code_alpha3'=>'MAC'],
            ['name'=>'Macedonia, The Former Yugoslav Republic Of','code_alpha2'=>'MK','code_alpha3'=>'MKD'],
            ['name'=>'Madagascar','code_alpha2'=>'MG','code_alpha3'=>'MDG'],
            ['name'=>'Malawi','code_alpha2'=>'MW','code_alpha3'=>'MWI'],
            ['name'=>'Malaysia','code_alpha2'=>'MY','code_alpha3'=>'MYS'],
            ['name'=>'Maldives','code_alpha2'=>'MV','code_alpha3'=>'MDV'],
            ['name'=>'Mali','code_alpha2'=>'ML','code_alpha3'=>'MLI'],
            ['name'=>'Malta','code_alpha2'=>'MT','code_alpha3'=>'MLT'],
            ['name'=>'Marshall Islands','code_alpha2'=>'MH','code_alpha3'=>'MHL'],
            ['name'=>'Martinique','code_alpha2'=>'MQ','code_alpha3'=>'MTQ'],
            ['name'=>'Mauritania','code_alpha2'=>'MR','code_alpha3'=>'MRT'],
            ['name'=>'Mauritius','code_alpha2'=>'MU','code_alpha3'=>'MUS'],
            ['name'=>'Mayotte','code_alpha2'=>'YT','code_alpha3'=>'MYT'],
            ['name'=>'Mexico','code_alpha2'=>'MX','code_alpha3'=>'MEX'],
            ['name'=>'Micronesia, Federated States of','code_alpha2'=>'FM','code_alpha3'=>'FSM'],
            ['name'=>'Moldova','code_alpha2'=>'MD','code_alpha3'=>'MDA'],
            ['name'=>'Monaco','code_alpha2'=>'MC','code_alpha3'=>'MCO'],
            ['name'=>'Mongolia','code_alpha2'=>'MN','code_alpha3'=>'MNG'],
            ['name'=>'Montenegro','code_alpha2'=>'ME','code_alpha3'=>'MNE'],
            ['name'=>'Montserrat','code_alpha2'=>'MS','code_alpha3'=>'MSR'],
            ['name'=>'Morocco','code_alpha2'=>'MA','code_alpha3'=>'MAR'],
            ['name'=>'Mozambique','code_alpha2'=>'MZ','code_alpha3'=>'MOZ'],
            ['name'=>'Namibia','code_alpha2'=>'NA','code_alpha3'=>'NAM'],
            ['name'=>'Nauru','code_alpha2'=>'NR','code_alpha3'=>'NRU'],
            ['name'=>'Nepal','code_alpha2'=>'NP','code_alpha3'=>'NPL'],
            ['name'=>'Netherlands','code_alpha2'=>'NL','code_alpha3'=>'NLD'],
            ['name'=>'New Caledonia','code_alpha2'=>'NC','code_alpha3'=>'NCL'],
            ['name'=>'New Zealand','code_alpha2'=>'NZ','code_alpha3'=>'NZL'],
            ['name'=>'Nicaragua','code_alpha2'=>'NI','code_alpha3'=>'NIC'],
            ['name'=>'Niger','code_alpha2'=>'NE','code_alpha3'=>'NER'],
            ['name'=>'Nigeria','code_alpha2'=>'NG','code_alpha3'=>'NGA'],
            ['name'=>'Niue','code_alpha2'=>'NU','code_alpha3'=>'NIU'],
            ['name'=>'Norfolk Island','code_alpha2'=>'NF','code_alpha3'=>'NFK'],
            ['name'=>'Northern Mariana Islands','code_alpha2'=>'MP','code_alpha3'=>'MNP'],
            ['name'=>'Norway','code_alpha2'=>'NO','code_alpha3'=>'NOR'],
            ['name'=>'Oman','code_alpha2'=>'OM','code_alpha3'=>'OMN'],
            ['name'=>'Pakistan','code_alpha2'=>'PK','code_alpha3'=>'PAK'],
            ['name'=>'Palau','code_alpha2'=>'PW','code_alpha3'=>'PLW'],
            ['name'=>'Palestinian Territory, Occupied','code_alpha2'=>'PS','code_alpha3'=>'PSE'],
            ['name'=>'Panama','code_alpha2'=>'PA','code_alpha3'=>'PAN'],
            ['name'=>'Papua New Guinea','code_alpha2'=>'PG','code_alpha3'=>'PNG'],
            ['name'=>'Paraguay','code_alpha2'=>'PY','code_alpha3'=>'PRY'],
            ['name'=>'Peru','code_alpha2'=>'PE','code_alpha3'=>'PER'],
            ['name'=>'Philippines','code_alpha2'=>'PH','code_alpha3'=>'PHL'],
            ['name'=>'Pitcairn','code_alpha2'=>'PN','code_alpha3'=>'PCN'],
            ['name'=>'Poland','code_alpha2'=>'PL','code_alpha3'=>'POL'],
            ['name'=>'Portugal','code_alpha2'=>'PT','code_alpha3'=>'PRT'],
            ['name'=>'Puerto Rico','code_alpha2'=>'PR','code_alpha3'=>'PRI'],
            ['name'=>'Qatar','code_alpha2'=>'QA','code_alpha3'=>'QAT'],
            ['name'=>'Reunion','code_alpha2'=>'RE','code_alpha3'=>'REU'],
            ['name'=>'Romania','code_alpha2'=>'RO','code_alpha3'=>'ROU'],
            ['name'=>'Russian Federation','code_alpha2'=>'RU','code_alpha3'=>'RUS'],
            ['name'=>'Rwanda','code_alpha2'=>'RW','code_alpha3'=>'RWA'],
            ['name'=>'Saint Barthélemy','code_alpha2'=>'BL','code_alpha3'=>'BLM'],
            ['name'=>'Saint Helena, Ascension And Tristan Da Cunha','code_alpha2'=>'SH','code_alpha3'=>'SHN'],
            ['name'=>'Saint Kitts and Nevis','code_alpha2'=>'KN','code_alpha3'=>'KNA'],
            ['name'=>'Saint Lucia','code_alpha2'=>'LC','code_alpha3'=>'LCA'],
            ['name'=>'Saint Martin (French Part)','code_alpha2'=>'MF','code_alpha3'=>'MAF'],
            ['name'=>'Saint Pierre and Miquelon','code_alpha2'=>'PM','code_alpha3'=>'SPM'],
            ['name'=>'Saint Vincent and the Grenadines','code_alpha2'=>'VC','code_alpha3'=>'VCT'],
            ['name'=>'Samoa','code_alpha2'=>'WS','code_alpha3'=>'WSM'],
            ['name'=>'San Marino','code_alpha2'=>'SM','code_alpha3'=>'SMR'],
            ['name'=>'Sao Tome and Principe','code_alpha2'=>'ST','code_alpha3'=>'STP'],
            ['name'=>'Saudi Arabia','code_alpha2'=>'SA','code_alpha3'=>'SAU'],
            ['name'=>'Senegal','code_alpha2'=>'SN','code_alpha3'=>'SEN'],
            ['name'=>'Serbia','code_alpha2'=>'RS','code_alpha3'=>'SRB'],
            ['name'=>'Seychelles','code_alpha2'=>'SC','code_alpha3'=>'SYC'],
            ['name'=>'Sierra Leone','code_alpha2'=>'SL','code_alpha3'=>'SLE'],
            ['name'=>'Singapore','code_alpha2'=>'SG','code_alpha3'=>'SGP'],
            ['name'=>'Sint Maarten','code_alpha2'=>'SX','code_alpha3'=>'SXM'],
            ['name'=>'Slovakia','code_alpha2'=>'SK','code_alpha3'=>'SVK'],
            ['name'=>'Slovenia','code_alpha2'=>'SI','code_alpha3'=>'SVN'],
            ['name'=>'Solomon Islands','code_alpha2'=>'SB','code_alpha3'=>'SLB'],
            ['name'=>'Somalia','code_alpha2'=>'SO','code_alpha3'=>'SOM'],
            ['name'=>'South Africa','code_alpha2'=>'ZA','code_alpha3'=>'ZAF'],
            ['name'=>'South Georgia and the South Sandwich Islands','code_alpha2'=>'GS','code_alpha3'=>'SGS'],
            ['name'=>'South Ossetia','code_alpha2'=>'OS','code_alpha3'=>'OST'],
            ['name'=>'South Sudan','code_alpha2'=>'SS','code_alpha3'=>'SSD'],
            ['name'=>'Spain','code_alpha2'=>'ES','code_alpha3'=>'ESP'],
            ['name'=>'Sri Lanka','code_alpha2'=>'LK','code_alpha3'=>'LKA'],
            ['name'=>'Sudan','code_alpha2'=>'SD','code_alpha3'=>'SDN'],
            ['name'=>'Suriname','code_alpha2'=>'SR','code_alpha3'=>'SUR'],
            ['name'=>'Svalbard and Jan Mayen','code_alpha2'=>'SJ','code_alpha3'=>'SJM'],
            ['name'=>'Sweden','code_alpha2'=>'SE','code_alpha3'=>'SWE'],
            ['name'=>'Switzerland','code_alpha2'=>'CH','code_alpha3'=>'CHE'],
            ['name'=>'Syrian Arab Republic','code_alpha2'=>'SY','code_alpha3'=>'SYR'],
            ['name'=>'Taiwan, Province of China','code_alpha2'=>'TW','code_alpha3'=>'TWN'],
            ['name'=>'Tajikistan','code_alpha2'=>'TJ','code_alpha3'=>'TJK'],
            ['name'=>'Tanzania, United Republic Of','code_alpha2'=>'TZ','code_alpha3'=>'TZA'],
            ['name'=>'Thailand','code_alpha2'=>'TH','code_alpha3'=>'THA'],
            ['name'=>'Timor-Leste','code_alpha2'=>'TL','code_alpha3'=>'TLS'],
            ['name'=>'Togo','code_alpha2'=>'TG','code_alpha3'=>'TGO'],
            ['name'=>'Tokelau','code_alpha2'=>'TK','code_alpha3'=>'TKL'],
            ['name'=>'Tonga','code_alpha2'=>'TO','code_alpha3'=>'TON'],
            ['name'=>'Trinidad and Tobago','code_alpha2'=>'TT','code_alpha3'=>'TTO'],
            ['name'=>'Tunisia','code_alpha2'=>'TN','code_alpha3'=>'TUN'],
            ['name'=>'Turkey','code_alpha2'=>'TR','code_alpha3'=>'TUR'],
            ['name'=>'Turkmenistan','code_alpha2'=>'TM','code_alpha3'=>'TKM'],
            ['name'=>'Turks and Caicos Islands','code_alpha2'=>'TC','code_alpha3'=>'TCA'],
            ['name'=>'Tuvalu','code_alpha2'=>'TV','code_alpha3'=>'TUV'],
            ['name'=>'Uganda','code_alpha2'=>'UG','code_alpha3'=>'UGA'],
            ['name'=>'Ukraine','code_alpha2'=>'UA','code_alpha3'=>'UKR'],
            ['name'=>'United Arab Emirates','code_alpha2'=>'AE','code_alpha3'=>'ARE'],
            ['name'=>'United Kingdom','code_alpha2'=>'GB','code_alpha3'=>'GBR'],
            ['name'=>'United States','code_alpha2'=>'US','code_alpha3'=>'USA'],
            ['name'=>'United States Minor Outlying Islands','code_alpha2'=>'UM','code_alpha3'=>'UMI'],
            ['name'=>'Uruguay','code_alpha2'=>'UY','code_alpha3'=>'URY'],
            ['name'=>'Uzbekistan','code_alpha2'=>'UZ','code_alpha3'=>'UZB'],
            ['name'=>'Vanuatu','code_alpha2'=>'VU','code_alpha3'=>'VUT'],
            ['name'=>'Venezuela','code_alpha2'=>'VE','code_alpha3'=>'VEN'],
            ['name'=>'Vietnam','code_alpha2'=>'VN','code_alpha3'=>'VNM'],
            ['name'=>'Virgin Islands, British','code_alpha2'=>'VG','code_alpha3'=>'VGB'],
            ['name'=>'Virgin Islands, U.S.','code_alpha2'=>'VI','code_alpha3'=>'VIR'],
            ['name'=>'Wallis and Futuna','code_alpha2'=>'WF','code_alpha3'=>'WLF'],
            ['name'=>'Western Sahara','code_alpha2'=>'EH','code_alpha3'=>'ESH'],
            ['name'=>'Yemen','code_alpha2'=>'YE','code_alpha3'=>'YEM'],
            ['name'=>'Zambia','code_alpha2'=>'ZM','code_alpha3'=>'ZMB'],
            ['name'=>'Zimbabwe','code_alpha2'=>'ZW','code_alpha3'=>'ZWE'],
            ['name'=>'Åland Islands','code_alpha2'=>'AX','code_alpha3'=>'ALA']]);
    }
}
