<?php

use Illuminate\Database\Seeder;

class DomainsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(){
        DB::table('domains')->insert([['source_id' => 104,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 105,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 117,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 120,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 121,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 122,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 123,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 124,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 125,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 4,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 126,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 127,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 128,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 11,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 7,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 44,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 84,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 116,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 98,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 118,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 20,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 103,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 129,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 130,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 131,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 132,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 133,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 134,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 101,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 41,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 38,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 102,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 63,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 2,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 93,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 31,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 115,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 45,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 144,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 143,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 142,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 141,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 140,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 139,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 138,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 137,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 136,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 110,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 109,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 108,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 148,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 149,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 150,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 145,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 146,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 147,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 85,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 154,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 155,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 156,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 151,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 152,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 153,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 163,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 164,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 165,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 166,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 167,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 169,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 170,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 171,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 172,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 173,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 174,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 178,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 179,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com'],
            ['source_id' => 180,'exclusive' => 'cranbu.com','exclusive_countries'=>'IN','common' => 'dromqo.com']]);
    }
}
