<?php
namespace App\Constants;

define('STATUS_CREATE_CAMPAIGN_IN_PROCESS',env('STATUS_CREATE_CAMPAIGN_IN_PROCESS'));
define('STATUS_CREATE_CAMPAIGN_MODERATION',env('STATUS_CREATE_CAMPAIGN_MODERATION'));
define('STATUS_CREATE_CAMPAIGN_DELETED_REQUEST',env('STATUS_CREATE_CAMPAIGN_DELETED_REQUEST'));
define('STATUS_CREATE_CAMPAIGN_DELETED',env('STATUS_CREATE_CAMPAIGN_DELETED'));
define('ERROR_PARAMS_TITLE',env('ERROR_PARAMS_TITLE'));
define('ERROR_CODE',env('ERROR_CODE'));
define('SUCCESS_CODE',(int)env('SUCCESS_CODE'));
define('STATUS_SUCCESS_DELETE_CAMPAIGN',env('STATUS_SUCCESS_DELETE_CAMPAIGN'));
define('ERROR_TYPEDATA_TITLE',env('ERROR_TYPEDATA_TITLE'));
define('STATUS_CREATE_CAMPAIGN_DOUBLE_EN',env('STATUS_CREATE_CAMPAIGN_DOUBLE_EN'));
define('STATUS_CREATE_CAMPAIGN_DELETED_EN',env('STATUS_CREATE_CAMPAIGN_DELETED_EN'));
define('SUCCESS_SETPLACEMENTS',env('SUCCESS_SETPLACEMENTS'));
define('ERROR_SETPLACEMENTS',env('ERROR_SETPLACEMENTS'));

define('NETWORK_USER_LOGIN', env('NETWORK_USER_LOGIN'));
define('NETWORK_USER_PASSWORD', env('NETWORK_USER_PASSWORD'));
define('NETWORK_USER_AGENT', env('NETWORK_USER_AGENT'));

define('API_KEY_CLICKADU', env('API_KEY_CLICKADU'));
define('API_BASE_URL_CLICKADU', env('API_BASE_URL_CLICKADU'));

define('API_KEY_CLICKAINE', env('API_KEY_CLICKAINE'));
define('API_BASE_URL_CLICKAINE', env('API_BASE_URL_CLICKAINE'));
define('API_TOKEN_CLICKAINE', env('API_TOKEN_CLICKAINE'));

define('URL_TELEGRAM_BOT', env('URL_TELEGRAM_BOT'));
define('API_KEY_TELEGRAM_BOT', env('API_KEY_TELEGRAM_BOT'));
define('CHAT_ID_MAIN_TELEGRAM', env('CHAT_ID_MAIN_TELEGRAM'));

define('STATUS_CAMPAIGN_MODERATION', env('STATUS_CAMPAIGN_MODERATION'));
define('STATUS_CAMPAIGN_RESUME', env('STATUS_CAMPAIGN_RESUME'));
define('STATUS_CAMPAIGN_STOPPED', env('STATUS_CAMPAIGN_STOPPED'));
define('STATUS_CAMPAIGN_REJECT', env('STATUS_CAMPAIGN_REJECT'));